### ISSUE TITLE
Tree Geometry Documentation

### ISSUE THREAD

**Issue by demi-solemma** [SolemmaLLC/ClimateStudioDocs#17]
- [x] version number?
- [x] workflow screenshots (accent numbers etc
     - [x] illuminance
     - [x] dailight
     - [x] galre
     - [x] randering
     - [x] radiation
     - [x] view
- [x] scene objects page
     - [x] explain which objects for which workflow

### tree page it self
- [x] tree page
- [x] select tree
- [x] add one tree
- [x] add multiple tree
- [x] tree block and exploding
- [x] only similarity transform
- [x] preselected dynamic leaf material

**Comment by demi-solemma** [comment]
![image](https://github.com/SolemmaLLC/ClimateStudioDocs/assets/81834605/80933111-c5d4-4f8d-9fc1-4f86f9e87e45)

**Comment by demi-solemma** [comment]
![image](https://github.com/SolemmaLLC/ClimateStudioDocs/assets/81834605/975e0a4e-6ca4-4de5-b249-1449c33a11b0)

**Comment by demi-solemma** [comment]
![screencapture-file-C-Users-DemiC-Documents-GitHub-ClimateStudioDocs-build-html-docs-tree-html-2023-11-28-16_18_37](https://github.com/SolemmaLLC/ClimateStudioDocs/assets/81834605/9ee4622c-8674-42b2-86c6-0842bd32e21c)

**Comment by demi-solemma** [comment]
![image](https://github.com/SolemmaLLC/ClimateStudioDocs/assets/81834605/05496260-8cee-4e65-b44e-aa523af7209c)

all 6 workflows now look something like this

**Comment by demi-solemma** [comment]
also added a Scene Objects page. which links to Luminaires, Tubular Daylight Devices, and Trees pages. 
this is mostly so we can have the "?" button on the workflow panel somehwere to link to.

**Comment by demi-solemma** [comment]
![screencapture-file-C-Users-DemiC-Documents-GitHub-ClimateStudioDocs-build-html-docs-sceneObjects-html-2023-11-29-17_45_33](https://github.com/SolemmaLLC/ClimateStudioDocs/assets/81834605/ddab8708-9976-4dd8-8125-83c948ec147f)

**Comment by JonSargent** [comment]
Can we drop "objects" and call it "scene assets"?

**Comment by JonSargent** [comment]
Also, you have "instance" and "definition" backwards in the layer table screenshot

**Comment by demi-solemma** [comment]
![image](https://github.com/SolemmaLLC/ClimateStudioDocs/assets/81834605/e5b93499-666f-4e30-a11c-9def3503d533)

**Comment by demi-solemma** [comment]
ok you are right it is more clear to call these block definition geometries

**Comment by demi-solemma** [comment]
![subPanel_trees_layer](https://github.com/SolemmaLLC/ClimateStudioDocs/assets/81834605/ae90059a-0f5e-4607-bcd2-6c2df7f6380d)
