### ISSUE TITLE
Luminaire Product and Luminaire Lib Documentation

### ISSUE THREAD

**Issue by demi-solemma** [SolemmaLLC/ClimateStudioDocs#25]
focus on screenshots
- new Luminaire UI (library, build luminaire, spectrum...)

**Comment by JonSargent** [comment]
@demi-solemma Small request... can you re-do this image with an IES file already uploaded? I think that will make the photometry description that follows easier to digest. Also the (**18**) tag is used twice...

![Image](https://github.com/user-attachments/assets/c2dc1afe-ea9b-4fa4-8c23-ac4a880fd491)

**Comment by JonSargent** [comment]
Maybe use a fun direct-indirect file like [this one](https://1drv.ms/u/s!AlC5WaN9VuJNhcs_OcBrkbwm7g4lzQ?e=hb864z)

![Image](https://github.com/user-attachments/assets/0e5a2e4a-7183-4e77-9184-ef85bbf81cba)

**Comment by demi-solemma** [comment]
yeah I was debating if we want the blank interface or with something selected ... :)

**Comment by demi-solemma** [comment]
`Solemma Dropbox\Development\Documentation\Screenshots\SubPanels\luminaire.ai`
started new Illiustrator file in the same SubPanels folder since the old one is getting really slow to save ...
