### ISSUE TITLE
Exterior Glazing (allow NoGlass and Custom Radiance Materials) Documentation update

### ISSUE THREAD

**Issue by demi-solemma** [SolemmaLLC/ClimateStudioDocs#28]
### Screen Shot Edits: 
- [x] opaque material - category name
- [x] exterior glazing 
  - [x] material - library drop down
  - [x] shade material - inset row
  - [x] shade control - up-down row
- [x] dynamic glass 
  - [x] category drop down renamed
  - [x] tint control
- [x] scheduled material
  - [x] library dropdown

**Comment by JonSargent** [comment]
Edits:
- [x] materials
- [x] exterior glass (shades)
- [x] exterior glass (ec)
- [x] interior glass
- [x] custom materials
- [x] leaf
- [x] snow
- [x] scheduled
